const xlsx = require('node-xlsx')
const fs = require('fs')
const data = [
  {"name": "AdobeSongStd-Light", "dirPath": "AdobeSongStd-Light", "value": "AdobeSongStd-Light,Microsoft YaHei"},
  {"name": "Arial", "dirPath": "Arial", "value": "Arial,Microsoft YaHei"},
  {"name": "AHRONBD", "dirPath": "AHRONBD", "value": "AHRONBD,Microsoft YaHei"},
  {"name": "Arial Black", "dirPath": "Arial_Black", "value": "Arial Black,Microsoft YaHei"},
  {"name": "Arial Rounded Bold", "dirPath": "Arial_Rounded_Bold", "value": "Arial Rounded Bold,Microsoft YaHei"},
  {"name": "Arial Unicode", "dirPath": "Arial_Unicode", "value": "Arial Unicode,Microsoft YaHei"},
  {"name": "Calibri", "dirPath": "Calibri", "value": "Calibri,Microsoft YaHei"},
  {"name": "calibrib", "dirPath": "calibrib", "value": "calibrib,Microsoft YaHei"},
  {"name": "calibrii", "dirPath": "calibrii", "value": "calibrii,Microsoft YaHei"},
  {"name": "calibril", "dirPath": "calibril", "value": "calibril,Microsoft YaHei"},
  {"name": "calibrili", "dirPath": "calibrili", "value": "calibrili,Microsoft YaHei"},
  {"name": "calibriz", "dirPath": "calibriz", "value": "calibriz,Microsoft YaHei"},
  {"name": "CHILLER", "dirPath": "CHILLER", "value": "CHILLER,Microsoft YaHei"},
  {"name": "COOPBL", "dirPath": "COOPBL", "value": "COOPBL,Microsoft YaHei"},
  {"name": "DIN-MediumItalic", "dirPath": "DIN-MediumItalic", "value": "DIN-MediumItalic,Microsoft YaHei"},
  {"name": "Helvetica", "dirPath": "Helvetica", "value": "Helvetica,Microsoft YaHei"},
  {"name": "SohoGothicPro-Regular", "dirPath": "SohoGothicPro-Regular", "value": "SohoGothicPro-Regular,Microsoft YaHei"},
  {"name": "TektonPro-BoldCond", "dirPath": "TektonPro-BoldCond", "value": "TektonPro-BoldCond,Microsoft YaHei"},
  {"name": "Times New Roman", "dirPath": "Times_New_Roman", "value": "Times New Roman,Microsoft YaHei","alias":"times new roman"},
  {"name": "Times New Roman", "dirPath": "Times_New_Roman_Italic", "value": "Times New Roman,Microsoft YaHei", "fontStyle": "italic"},
  {"name": "Times New Roman", "dirPath": "Times_New_Roman_Bold", "value": "Times New Roman,Microsoft YaHei", "fontWeight": "bold"},
  {"name": "Times New Roman", "dirPath": "Times_New_Roman_Bold_Italic", "value": "Times New Roman,Microsoft YaHei", "fontStyle": "italic", "fontWeight": "bold"},
  {"name": "黑体", "dirPath": "heiti", "value": "黑体"},
  {"name": "黑体", "dirPath": "heiti_bold", "value": "黑体", "fontWeight": "bold"},
  {"name": "GOTHIC", "dirPath": "GOTHIC", "value": "GOTHIC,Microsoft YaHei"},
  {"name": "GOTHIC", "dirPath": "GOTHICI", "value": "GOTHIC,Microsoft YaHei", "fontStyle": "italic"},
  {"name": "GOTHIC", "dirPath": "GOTHICB", "value": "GOTHIC,Microsoft YaHei", "fontWeight": "bold"},
  {"name": "GOTHIC", "dirPath": "GOTHICBI", "value": "GOTHIC,Microsoft YaHei", "fontStyle": "italic", "fontWeight": "bold"},
  {"name": "Source_CUP_Infant", "value": "Source_CUP_Infant,Microsoft YaHei", "dirPath": "Source_CUP_Infant_Bold_Italic", "fontStyle": "italic", "fontWeight": "bold"},
  {"name": "Source_CUP_Infant", "value": "Source_CUP_Infant,Microsoft YaHei", "dirPath": "Source_CUP_Infant_Bold", "fontWeight": "bold"},
  {"name": "Source_CUP_Infant", "value": "Source_CUP_Infant,Microsoft YaHei", "dirPath": "Source_CUP_Infant_Italic", "fontStyle": "italic"},
  {"name": "Source_CUP_Infant", "value": "Source_CUP_Infant,Microsoft YaHei", "dirPath": "Source_CUP_Infant_Regular"},
  {"name": "Source_CUP_Infant_Black", "dirPath": "Source_CUP_Infant_Black_Italic", "value": "Source_CUP_Infant_Black,Microsoft YaHei", "fontStyle": "italic"},
  {"name": "Source_CUP_Infant_Black", "dirPath": "Source_CUP_Infant_Black", "value": "Source_CUP_Infant_Black,Microsoft YaHei"},
  {"name": "Source_CUP_Infant_Light", "dirPath": "Source_CUP_Infant_Light_Italic", "value": "Source_CUP_Infant_Light,Microsoft YaHei", "fontStyle": "italic"},
  {"name": "Source_CUP_Infant_Light", "dirPath": "Source_CUP_Infant_Light", "value": "Source_CUP_Infant_Light,Microsoft YaHei"},
  {"name": "Source_CUP_Infant_Semibold", "dirPath": "Source_CUP_Infant_Semibold_Italic", "value": "Source_CUP_Infant_Semibold,Microsoft YaHei", "fontStyle": "italic"},
  {"name": "Source_CUP_Infant_Semibold", "dirPath": "Source_CUP_Infant_Semibold", "value": "Source_CUP_Infant_Semibold,Microsoft YaHei"},
  {"name": "GB PINYINOK", "dirPath": "GB_PINYINOK", "value": "GB PINYINOK,Microsoft YaHei"},
  {"name": "GB PINYINOK-A", "dirPath": "GB_PINYINOK-A", "value": "GB PINYINOK-A,Microsoft YaHei"},
  {"name": "GB PINYINOK-B", "dirPath": "GB_PINYINOK-B", "value": "GB PINYINOK-B,Microsoft YaHei"},
  {"name": "GB PINYINOK-C", "dirPath": "GB_PINYINOK-C", "value": "GB PINYINOK-C,Microsoft YaHei"},
  {"name": "GB PINYINOK-D", "dirPath": "GB_PINYINOK-D", "value": "GB PINYINOK-D,Microsoft YaHei"},
  {"name": "GB PINYINOK-F", "dirPath": "GB_PINYINOK-F", "value": "GB PINYINOK-F,Microsoft YaHei"},
  {"name": "宋体", "dirPath": "songti", "value": "宋体"},
  {"name": "楷体", "dirPath": "kaiti", "value": "楷体"},
  {"name": "Microsoft YaHei", "dirPath": "Microsoft_YaHei", "value": "Microsoft YaHei"},
  {"name": "华文中宋", "dirPath": "HWzhongsong", "value": "华文中宋"},
  {"name": "STHeiti", "dirPath": "HWHT", "value": "STHeiti"},
  {"name": "华康手札体", "dirPath": "shouzhati", "value": "华康手札体"},
  {"name": "方正准圆简体", "dirPath": "FZzhunyuanJ", "value": "方正准圆简体"},
  {"name": "方正准圆繁体", "dirPath": "FZzhunyuanF", "value": "方正准圆繁体"},
  {"name": "方正兰亭中黑", "dirPath": "FZlantingZH", "value": "方正兰亭中黑"},
  {"name": "方正韵动中黑", "dirPath": "FZyundongZH", "value": "方正韵动中黑"},
  {"name": "方正正黑简体", "dirPath": "FZzhengheiJ", "value": "方正正黑简体"},
  {"name": "方正古隶简体", "dirPath": "FZguliJ", "value": "方正古隶简体"},
  {"name": "方正黄草简体", "dirPath": "FZhuangcaoJ", "value": "方正黄草简体"},
  {"name": "方正兰亭刊宋", "dirPath": "FZlantingkansong", "value": "方正兰亭刊宋"},
  {"name": "方正粗活意简体", "dirPath": "FZCHYJW", "value": "方正粗活意简体"},
  {"name": "方正粗倩简体", "dirPath": "FZCQJW", "value": "方正粗倩简体"},
  {"name": "方正粗宋简体", "dirPath": "FZCSJW", "value": "方正粗宋简体"},
  {"name": "方正大黑简体", "dirPath": "FZDHTJW", "value": "方正大黑简体"},
  {"name": "方正汉真广标简体", "dirPath": "FZHZGBJW", "value": "方正汉真广标简体"},
  {"name": "方正剪纸简体", "dirPath": "FZJZJW", "value": "方正剪纸简体"},
  {"name": "方正卡通简体", "dirPath": "FZKATJW", "value": "方正卡通简体"},
  {"name": "方正兰亭粗黑简体", "dirPath": "FZLTCHJW", "value": "方正兰亭粗黑简体"},
  {"name": "方正兰亭细黑简体", "dirPath": "FZLTXIHJW", "value": "方正兰亭细黑简体"},
  {"name": "方正兰亭中黑简体", "dirPath": "FZLTZHJW", "value": "方正兰亭中黑简体"},
  {"name": "方正喵呜体", "dirPath": "FZMWFont", "value": "方正喵呜体"},
  {"name": "方正胖头鱼简体", "dirPath": "FZPTYJW", "value": "方正胖头鱼简体"},
  {"name": "方正胖娃简体", "dirPath": "FZPWJW", "value": "方正胖娃简体"},
  {"name": "方正启体简体", "dirPath": "FZQTJW_0", "value": "方正启体简体"},
  {"name": "方正少儿简体", "dirPath": "FZSEJW", "value": "方正少儿简体"},
  {"name": "方正水柱简体", "dirPath": "FZSZJW", "value": "方正水柱简体"},
  {"name": "方正粗圆简体", "dirPath": "FZY4JW", "value": "方正粗圆简体"},
  {"name": "方正硬笔行书简体", "dirPath": "FZYBXSJW", "value": "方正硬笔行书简体"},
  {"name": "方正毡笔黑简体", "dirPath": "FZZBHJW", "value": "方正毡笔黑简体"},
  {"name": "方正稚艺简体", "dirPath": "FZZHYJW", "value": "方正稚艺简体"},
  {"name": "方正中倩简体", "dirPath": "FZZQJW", "value": "方正中倩简体"},
  {"name": "方正综艺简体", "dirPath": "FZZYJW", "value": "方正综艺简体"},
  {"name": "方正榜书行简", "dirPath": "FZBSHJW", "value": "方正榜书行简"},
  {"name": "方正海体楷书简", "dirPath": "FZHTKSJW", "value": "方正海体楷书简"},
  {"name": "方正隶变简", "dirPath": "FZLBJW", "value": "方正隶变简"},
  {"name": "方正隶书简体", "dirPath": "FZLSJW", "value": "方正隶书简体"},
  {"name": "方正苏新诗楷体", "dirPath": "FZSXSKT", "value": "方正苏新诗楷体"},
  {"name": "HOUSEARAMA-KINGPIN", "dirPath": "HOUSEARAMA-KINGPIN", "value": "HOUSEARAMA-KINGPIN,Microsoft YaHei"},
  {"name": "KINGPIN-LOWERIZED", "dirPath": "KINGPIN-LOWERIZED", "value": "KINGPIN-LOWERIZED,Microsoft YaHei"},
  {"name": "胡敬礼毛笔行书繁", "dirPath": "hujinglimaobixingshufan", "value": "胡敬礼毛笔行书繁"},
  {"name": "喜满体", "dirPath": "ximanti", "value": "喜满体"},
  {"name": "沐瑶软笔手", "dirPath": "Muyao-Softbrush", "value": "沐瑶软笔手"},
  {"name": "xesEnglish", "dirPath": "xesEnglish", "value": "xesEnglish,Microsoft YaHei","alias":"xesEnglishFont"},
  {"name": "xesEnglish Bold", "dirPath": "xesEnglish_Bold", "value": "xesEnglish Bold,Microsoft YaHei"},
  {"name": "xesEnglish Bold", "dirPath": "xesEnglish_Bold_Italic", "value": "xesEnglish,Microsoft YaHei" , "fontStyle":"italic" },
  {"name": "xesEnglish Semibold", "dirPath": "xesEnglish_Semibold", "value": "xesEnglish Semibold,Microsoft YaHei" },
  {"name": "xesEnglish Semibold", "dirPath": "xesEnglish_Semibold_Italic", "value": "xesEnglish Semibold,Microsoft YaHei", "fontStyle":"italic" },
  {"name": "xesEnglish Semibold Italic", "dirPath": "xesEnglish_Semibold_Italic", "value": "xesEnglish Semibold Italic,Microsoft YaHei"},
  {"name": "xesEnglish Black", "dirPath": "xesEnglish_Black", "value": "xesEnglish Black,Microsoft YaHei"},
  {"name": "xesEnglish Black", "dirPath": "xesEnglish_Black_Italic", "value": "xesEnglish Black,Microsoft YaHei", "fontStyle":"italic" },
  {"name": "xesEnglish Light", "dirPath": "xesEnglish_Light", "value": "xesEnglish Light,Microsoft YaHei"},
  {"name": "xesEnglish Light", "dirPath": "xesEnglish_Light_Italic", "value": "xesEnglish Light,Microsoft YaHei", "fontStyle":"italic"}
]

const data1 = [['name','dirPath','value','fontStyle','fontWeight','alias']];
for(let i = 0;i<data.length;i++){
  let item = data[i];
  let a = [];
  a.push(...[item.name,item.dirPath,item.value,item.fontStyle,item.fontWeight,item.alias]);
  data1.push(a);
}
var buffer = xlsx.build([{name: "sheet1", data: data1}]); // Returns a buffer
fs.writeFileSync('font.xlsx',buffer)